export const ActionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTED_PRODUCT: 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
    CART_IS_OPEN: 'CART_IS_OPEN',
    ADD_To_CART: 'ADD_To_CART',
    INC_CART_QUN: 'INC_CART_QUN',
    DEC_CART_QUN: 'DEC_CART_QUN',
    SEARCH_ITEM: 'SEARCH_ITEM',
    FILTER_CATEGORY: 'FILTER_CATEGORY',
}